# Generated by Django 6.0 on 2026-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian')], default='en', help_text='Preferred language for AI responses and UI', max_length=10),
        ),
    ]
