# Generated by Django 6.0.4 on 2026-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chatmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the file in the documents directory', max_length=255, unique=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
